package simpledb;


import java.util.*;
import java.io.*;


/**
 * Each instance of HeapPage stores data for one page of HeapFiles and 
 * implements the Page interface that is used by BufferPool.
 *
 * @see HeapFile
 * @see BufferPool
 *
 */
public class HeapPage implements Page {


    private HeapPageId pid;
    private TupleDesc td;
    private byte header[];
    Tuple tuples[];
    private int numSlots;


    byte[] oldData;
    private boolean dirty;
    private TransactionId dirtyTid;


    /**
     * Create a HeapPage from a set of bytes of data read from disk.
     * The format of a HeapPage is a set of header bytes indicating
     * the slots of the page that are in use, some number of tuple slots.
     *  Specifically, the number of tuples is equal to: <p>
     *          floor((BufferPool.PAGE_SIZE*8) / (tuple size * 8 + 1))
     * <p> where tuple size is the size of tuples in this
     * database table, which can be determined via {@link Catalog#getTupleDesc}.
     * The number of 8-bit header words is equal to:
     * <p>
     *      ceiling(no. tuple slots / 8)
     * <p>
     * @see Database#getCatalog
     * @see Catalog#getTupleDesc
     * @see BufferPool#PAGE_SIZE
     */
    public HeapPage(HeapPageId id, byte[] data) throws IOException {
    	dirty = false;
    	dirtyTid = null;
    	
        this.pid = id;
        this.td = Database.getCatalog().getTupleDesc(id.getTableId());
        this.numSlots = getNumTuples();
        DataInputStream dis = new DataInputStream(new ByteArrayInputStream(data));


        // allocate and read the header slots of this page
        header = new byte[getHeaderSize()];
        for (int i=0; i<header.length; i++)
            header[i] = dis.readByte();


        try{
            // allocate and read the actual records of this page
            tuples = new Tuple[numSlots];
            for (int i=0; i<tuples.length; i++)
                tuples[i] = readNextTuple(dis,i);
        } catch(NoSuchElementException e) {
            e.printStackTrace();
        }
        dis.close();


        setBeforeImage();
    }


    /** Retrieve the number of tuples on this page.
        @return the number of tuples on this page
    */
    private int getNumTuples() {
        double bufferSize = BufferPool.PAGE_SIZE * 8;
        double tupleSize = (td.getSize() * 8) + 1;


        return (int) (bufferSize / tupleSize);
    }


    /**
     * Computes the number of bytes in the header of a page in a HeapFile with each tuple occupying tupleSize bytes
     * @return the number of bytes in the header of a page in a HeapFile with each tuple occupying tupleSize bytes
     */
    private int getHeaderSize() {
        double numTuples = getNumTuples();
        return (int) Math.ceil(numTuples / 8);
    }
    
    /** Return a view of this page before it was modified
        -- used by recovery */
    public HeapPage getBeforeImage(){
        try {
            return new HeapPage(pid,oldData);
        } catch (IOException e) {
            e.printStackTrace();
            //should never happen -- we parsed it OK before!
            System.exit(1);
        }
        return null;
    }
    
    public void setBeforeImage() {
        oldData = getPageData().clone();
    }


    /**
     * @return the PageId associated with this page.
     */
    public HeapPageId getId() {
        return this.pid;
    }


    /**
     * Suck up tuples from the source file.
     */
    private Tuple readNextTuple(DataInputStream dis, int slotId) throws NoSuchElementException {
        // if associated bit is not set, read forward to the next tuple, and
        // return null.
        if (!isSlotUsed(slotId)) {
            for (int i=0; i<td.getSize(); i++) {
                try {
                    dis.readByte();
                } catch (IOException e) {
                    throw new NoSuchElementException("error reading empty tuple");
                }
            }
            return null;
        }


        // read fields in the tuple
        Tuple t = new Tuple(td);
        RecordId rid = new RecordId(pid, slotId);
        t.setRecordId(rid);
        try {
            for (int j=0; j<td.numFields(); j++) {
                Field f = td.getFieldType(j).parse(dis);
                t.setField(j, f);
            }
        } catch (java.text.ParseException e) {
            e.printStackTrace();
            throw new NoSuchElementException("parsing error!");
        }


        return t;
    }


    /**
     * Generates a byte array representing the contents of this page.
     * Used to serialize this page to disk.
     * <p>
     * The invariant here is that it should be possible to pass the byte
     * array generated by getPageData to the HeapPage constructor and
     * have it produce an identical HeapPage object.
     *
     * @see #HeapPage
     * @return A byte array correspond to the bytes of this page.
     */
    public byte[] getPageData() {
        int len = BufferPool.PAGE_SIZE;
        ByteArrayOutputStream baos = new ByteArrayOutputStream(len);
        DataOutputStream dos = new DataOutputStream(baos);


        // create the header of the page
        for (int i=0; i<header.length; i++) {
            try {
                dos.writeByte(header[i]);
            } catch (IOException e) {
                // this really shouldn't happen
                e.printStackTrace();
            }
        }


        // create the tuples
        for (int i=0; i<tuples.length; i++) {


            // empty slot
            if (!isSlotUsed(i)) {
                for (int j=0; j<td.getSize(); j++) {
                    try {
                        dos.writeByte(0);
                    } catch (IOException e) {
                        e.printStackTrace();
                    }


                }
                continue;
            }


            // non-empty slot
            for (int j=0; j<td.numFields(); j++) {
                Field f = tuples[i].getField(j);
                try {
                    f.serialize(dos);
                
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }


        // padding
        int zerolen = BufferPool.PAGE_SIZE - (header.length + td.getSize() * tuples.length); //- numSlots * td.getSize();
        byte[] zeroes = new byte[zerolen];
        try {
            dos.write(zeroes, 0, zerolen);
        } catch (IOException e) {
            e.printStackTrace();
        }


        try {
            dos.flush();
        } catch (IOException e) {
            e.printStackTrace();
        }


        return baos.toByteArray();
    }


    /**
     * Static method to generate a byte array corresponding to an empty
     * HeapPage.
     * Used to add new, empty pages to the file. Passing the results of
     * this method to the HeapPage constructor will create a HeapPage with
     * no valid tuples in it.
     *
     * @return The returned ByteArray.
     */
    public static byte[] createEmptyPageData() {
        int len = BufferPool.PAGE_SIZE;
        return new byte[len]; //all 0
    }


    /**
     * Delete the specified tuple from the page;  the tuple should be updated to reflect
     *   that it is no longer stored on any page.
     * @throws DbException if this tuple is not on this page, or tuple slot is
     *         already empty.
     * @param t The tuple to delete
     */
    public void deleteTuple(Tuple t) throws DbException {
    	RecordId rid = t.getRecordId();
    	int slotId = rid.tupleno();
    	PageId pageId = rid.getPageId();
    	
    	if (pageId != this.pid) {
    		throw new DbException("Tuple t: " + t + " not on page");
    	}
    	
    	if (!isSlotUsed(slotId)) {
    		throw new DbException("Tuple t "  + t + " not on page");
    	}
    	
    	boolean used = false;
    	markSlotUsed(slotId, used);
    	this.tuples[slotId] = null;
    }


    /**
     * Adds the specified tuple to the page;  the tuple should be updated to reflect
     *  that it is now stored on this page.
     * @throws DbException if the page is full (no empty slots) or tupledesc
     *         is mismatch.
     * @param t The tuple to add.
     */
    public void insertTuple(Tuple t) throws DbException {
    	int slotId = getNextFreeSlot();
    	tuples[slotId] = t;
    	    	
    	RecordId newId = new RecordId(this.pid, slotId);
    	t.setRecordId(newId);
    	boolean used = true;
    	markSlotUsed(slotId, used);
    }


    /**
     * Marks this page as dirty/not dirty and record that transaction
     * that did the dirtying
     */
    public void markDirty(boolean dirty, TransactionId tid) {
    	this.dirty = dirty;
    	if (dirty) {
    		this.dirtyTid = tid;
    	} else {
    		this.dirtyTid = null;
    	}
    }


    /**
     * Returns the tid of the transaction that last dirtied this page, or null if the page is not dirty
     */
    public TransactionId isDirty() {
    	return this.dirtyTid;
    }


    /**
     * Returns the number of empty slots on this page.
     */
    public int getNumEmptySlots() {
        int tupleCount = getNumTuples();
        for (int i = 0; i < header.length; i++) {
            for (int slot = 0; slot < 8; slot++) {
                int slotNum = (i * 8) + slot;
                if (isSlotUsed(slotNum)) {
                    tupleCount--;
                }
            } // end inner for
        }


        return tupleCount;
    }
    
    public boolean hasFreeSlots() {
    	return getNumEmptySlots() > 0;
    }
    
    private int getNextFreeSlot() throws DbException {
    	for (int i = 0; i < header.length; i++) {
    		for (int slot = 0; slot < 8; slot++) {
    			int slotNum = (i * 8) + slot;
    			if (!isSlotUsed(slotNum)) return slotNum;
    		}
    	}
    	
    	throw new DbException("No free slots");
    }


    public int getNumValidTuples() {
        return getNumTuples() - getNumEmptySlots();
    }


    /**
     * Returns true if associated slot on this page is filled.
     */
    public boolean isSlotUsed(int i) {
        // Header is in bytes, slots are in bits
        int headerSlot = i / 8;
        int bit = i % 8;
        if (headerSlot >= header.length) {
            System.out.println("Header slot: " + headerSlot + " i: " + i);
            System.out.println("Tuple size: " + this.td.getSize());
            System.out.println("Max tuples: " + this.getNumTuples());
            System.out.println("Header size: " + this.getHeaderSize());
            System.out.println("Tuple size / 8: " + getNumTuples() / 8);
            System.out.println("Getting slot: " + headerSlot + " header length: " + header.length);
            assert (headerSlot < header.length);
        }
        byte headerInfo = header[headerSlot];
        int mask = 1 << bit;
        return (headerInfo & mask) > 0;
    }
    
    /**
     * Abstraction to fill or clear a slot on this page.
     */
    private void markSlotUsed(int i, boolean value) {
    	int headerSlot = i / 8;
    	int bit = i % 8;
    	byte headerInfo = header[headerSlot];
    	int mask = 0;
    	if (value) {
    		mask = 1 << bit;
    		mask = headerInfo | mask;
     	} else {
     		mask = headerInfo & ~(1 << bit);
     	}
    		
    	header[headerSlot] = (byte)mask;
    }


    /**
     * @return an iterator over all tuples on this page (calling remove on this iterator throws an UnsupportedOperationException)
     * (note that this iterator shouldn't return tuples in empty slots!)
     */
    public Iterator<Tuple> iterator() {
        return new HeapPageIterator(this);
    }
}
